### ISSUE TITLE
gym-optimal-intrusion-response cannot gym.make

### ISSUE THREAD

**Issue by wangzepeng111** [Limmen/gym-optimal-intrusion-response#1]
After I installed gym-optimal-intrusion-response

**# git clone and install from source
git clone https://github.com/Limmen/gym-optimal-intrusion-response
cd gym-optimal-intrusion-response
pip3 install -e .**

I use it by

**import gym
from gym_idsgame.envs import IdsGameEnv
env_name = "optimal-intrusion-response-v1"
env = gym.make(env_name)**

but I had a problem

**gym.error.UnregisteredEnv: No registered env with id: optimal-intrusion-response-v1**

**Comment by wangzepeng111** [comment]
Thank you for your response .When I try to import from gym_optimal_intrusion_response.envs.optimal_intrusion_response_env import OptimalIntrusionResponseEnv ,No module named 'gym_pycr_ctf'.I feel sorry that i cannot to resolve it by myself

**Comment by Limmen** [comment]
Hi, I recommend using this environment for now: https://github.com/Limmen/gym-idsgame

I will release and update to this environment in the future to make it more stable, I will let you know then. 

Best-
Kim

**Comment by wangzepeng111** [comment]
Thank you
